### PR TITLE
Refacto statinamic

### LINKED ISSUE #471: Make the website U N I V E R S A L
## never forget 

> at https://github.com/putaindecode/putaindecode.fr/blob/master/scripts/build.js#L117, add `reactRender: “renderToString”`

### PR DESCRIPTION
**Pull request by MoOx**
Close #471 

Missing (to be done before merging):

- [x] rss
- [x] use of `<Link>` instead of `<a>`
- [x] images references in .md are broken
- [x] non fr posts are visible (should not for now)
- [ ] 404 page is ugly
- [x] CNAME is probably missing from the build
- [x] see how to improve contributrors.json

### CODE REVIEW

**Comment by MoOx** [comment]
Reminder: travis is errored with node 4.x.

**Comment by magsout** [comment]
cooool

tumblr_inline_nr4vqrceq31s7hc7q_500

**Comment by magsout** [comment]
Maybe needs revision but 
✔  `use of <Link> instead of <a> `

**Comment by MoOx** [comment]
Thanks @magsout, looks good!

**Comment by MoOx** [comment]
@putaindecode/authors For contributors.json, if we remove it from git, everyone that will want to build the website will probably need a github token as env var (since github api without token is limited to 60 queries per hour) as soon as we will have more than 60 authors. Do you think that might be a problem?

**Comment by MoOx** [comment]
Note: we have already more that 60 contributors so this will be a requirement :/

**Comment by MoOx** [comment]
A token under GH_TOKEN or GITHUB_TOKEN is now required to build the app (at least the first time, if you don't have the contributors.json cache, which is now local).
This contributors.json versionned has always been awful to update anyway.

**Comment by MoOx** [comment]
For some md code that isn't parsed (some images): I changed the engine from marked to markdown-it and it seems markdown-it stop parsing md when it encounter some html. This means that md in html tags aren't converted (that kind of make sense).
We will need to fix all post that are in this case. Youpi quoi.

**Comment by magsout** [comment]
> We will need to fix all post that are in this case. Youpi quoi.

Seems ok, I just sent the fix (2 posts)

**Comment by magsout** [comment]
I just sent some improvement about `NotFound` page. It's like the old 404.

**Comment by magsout** [comment]
>Do you think all the css is required?

Maybe not.

**Comment by MoOx** [comment]
Note:for 404.html, we need this to be handled https://github.com/MoOx/statinamic/issues/47

**Comment by MoOx** [comment]
404.html will require more time, so we might skip it atm and add it later (we will have github 404 for a while, not a big deal imo).

I will try to handle last things (hide non fr content, CNAME + adjust error for contributors.json) this evening in order to merge this asap.

**Comment by MoOx** [comment]
I have added some new ajustements.

```console
[10:52:06 PM] [statinamic/lib/static] ✓ Static html files: 72 files written
34s
```

**Comment by MoOx** [comment]
Here it is. I am merging this and we will see what happen then.
Feel free to review/blame :)

**Comment by MoOx** [comment]
On major issue is present: collection is fucked up and only contain around 10 posts. I am on it.

**Comment by MoOx** [comment]
(related to travis speed)

**Comment by magsout** [comment]
chuck-berry-duckwalk-1373308812

**Comment by MoOx** [comment]
Bug of the collection fixed by statinamic 0.4.1

**Pull request merged**
