### PR TITLE
Little change designs

### LINKED ISSUE #374: Inliner les icons svg afin de pouvoir récupérer les couleurs :)

### PR DESCRIPTION
**Pull request by MoOx**
I was enjoying my cup of tea and wanted to try some stuff.
Tell me what you think.

# Before

## Homepage
screen shot 2015-05-19 at 14 24 15
## Post
screen shot 2015-05-19 at 14 24 22
## Post with image
screen shot 2015-05-19 at 14 24 32

# After

## Homepage
screen shot 2015-05-19 at 14 24 43
## Post
screen shot 2015-05-19 at 14 24 48
## Post with image
screen shot 2015-05-19 at 14 24 54

Close #374

### CODE REVIEW

**Comment by Nyalab** [comment]
why the fuck not? it seems pretty, and a dash of change is never bad. it may lack a bit a color on the post page, but it is not that important. LGTM :shipit:

**Comment by kud** [comment]
Ca va devenir bien sexy cette histoire :D merci @MoOx

**Comment by skinnyfoetusboy** [comment]
Subtle, I like it.

**Comment by Macxim** [comment]
I like it, although as @Nyalab said, the post pages without header image look a bit empty.
Nice work, thanks :+1:

**Comment by MoOx** [comment]
>  the post pages without header image look a bit empty.

Same feeling, we might find something new to fix this feeling :)

**Comment by Nyalab** [comment]
yes, don't worry, it is better even like that, good job mate

**Comment by magsout** [comment]
Maybe removed h1 margin ?

**Comment by MoOx** [comment]
> Maybe removed h1 margin ?

If you talk about posts without images, I think we might be able to handle that after. I will when I get more time.

**Pull request merged**
