### PR TITLE
fix typo PageError.title

### PR DESCRIPTION
**Pull request by revolunet**

### CODE REVIEW

**Comment by MoOx** [comment]
Nice catch. Thanks !
(PS: where did you get a 404? Just curious ^^)

**Comment by MoOx** [comment]
Note: I need to double check why the build is broken (obviously not your fault)

**Comment by revolunet** [comment]
from the homepage : http://putaindecode.fr/putaindecode/putaindecode.fr/graphs/contributors

**Comment by MoOx** [comment]
I should have fixed the issue of the build in master, so should not happen :)

**Pull request merged**
