### PR TITLE
Fix: Element a not allowed as child of element ul in this context.

### PR DESCRIPTION
**Pull request by euskadi31**

### CODE REVIEW

**Comment by MoOx** [comment]
Nice but I think it's still not better than before, only on li/a should be in the loop.

**Comment by MoOx** [comment]
I think this one is better https://github.com/putaindecode/putaindecode.fr/pull/340

**Comment by euskadi31** [comment]
Yep bien vu ;)

**Comment by MoOx** [comment]
Merci en tout cas !

**Comment by euskadi31** [comment]
De rien ;)

**Pull request closed without merging**
