### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by AngeliqueH**
I was having a good time until I read this little tiny part, please take in account the 1% of girls that love programming :)

### CODE REVIEW

**Comment by kud** [comment]
J'avoue, c'est un peu la honte. Je me désolidarise de ces propos. (Ouais parait que c'est bien de faire ça en c'moment).

**Comment by bloodyowl** [comment]
what is the issue with that? it's just a play on words. if we start to think about who some wording might offend, we wouldn't be able to keep that tone we have and we would start making a difference between people and categories of people. I don't like that.

**Comment by MoOx** [comment]
I've to admit that I never liked that much this one.
+1 for merging the PR or +1 to find another expression. `marcassin` is fun, maybe we can do better.

**Comment by Nyalab** [comment]
Of course! So offensive! So discriminant! :disappointed:

**Pull request merged**
